// Code generated by cmd/codegen from https://github.com/elokore/cimgui-go-vulkan.
// DO NOT EDIT.

package opengl3

// #include <stdlib.h>
// #include <memory.h>
// #include "wrapper.h"
// #include "typedefs.h"
// #include "../../imgui/extra_types.h"
import "C"
