// Code generated by cmd/codegen from https://github.com/elokore/cimgui-go-vulkan.
// DO NOT EDIT.

#pragma once

#include "wrapper.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif
