// Code generated by cmd/codegen from https://github.com/elokore/cimgui-go-vulkan.
// DO NOT EDIT.

package glfw

// #include <stdlib.h>
// #include <memory.h>
// #include "wrapper.h"
// #include "typedefs.h"
// #include "../../imgui/extra_types.h"
import "C"
import "github.com/elokore/cimgui-go-vulkanulkan/internal"

type GLFWwindow struct {
	CData *C.GLFWwindow
}

// Handle returns C version of GLFWwindow and its finalizer func.
func (self *GLFWwindow) Handle() (result *C.GLFWwindow, fin func()) {
	return self.CData, func() {}
}

// NewGLFWwindowFromC creates GLFWwindow from its C pointer.
// SRC ~= *C.GLFWwindow
func NewGLFWwindowFromC[SRC any](cvalue SRC) *GLFWwindow {
	return &GLFWwindow{CData: internal.ReinterpretCast[*C.GLFWwindow](cvalue)}
}
