// Code generated by cmd/codegen from https://github.com/elokore/cimgui-go-vulkan.
// DO NOT EDIT.

#pragma once

#include "../../cwrappers/cimgui.h"
#include "../../cwrappers/cimgui_impl.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif
