// Code generated by cmd/codegen from https://github.com/LamkasDev/cimgui-go-vulkan.
// DO NOT EDIT.


#pragma once


#include "../cwrappers/cimguizmo.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif